var first = prompt("What is your first name?")
var last = prompt("What is your last name?")
var age = prompt("How old are you?")
console.log("Nice to meet you " + first + " " + last)
console.log("According to my knowledge, you are " + age + " years old")
